######################################################################
# Automatically generated by qmake (3.0) Mon Oct 20 05:38:03 2014
######################################################################

TEMPLATE = app
TARGET = exe
QT += core network
INCLUDEPATH += .

# Input
SOURCES += main.cpp
