######################################################################
# Automatically generated by qmake (3.0) Wed Oct 1 05:19:24 2014
######################################################################

TEMPLATE = app
TARGET = spreadshit

QT += core gui widgets

INCLUDEPATH += .

# Input
HEADERS += mainwindow.hpp spreadsheet.hpp
SOURCES += main.cpp mainwindow.cpp
RESOURCES += spreadsheet.qrc
