######################################################################
# Automatically generated by qmake (3.0) Thu Oct 2 01:57:36 2014
######################################################################

TEMPLATE = app
TARGET = dictionary

QT += core gui widgets

INCLUDEPATH += .

# Input
HEADERS += dmainwindow.hpp user_gui.hpp user.hpp
SOURCES += dmainwindow.cpp user_gui.cpp main.cpp
