######################################################################
# Automatically generated by qmake (3.0) Thu Aug 28 13:30:03 2014
######################################################################

TEMPLATE = app
TARGET = making_connections_exe

QT += core gui widgets

INCLUDEPATH += .

# Input
SOURCES += main.cpp
