######################################################################
# Automatically generated by qmake (3.0) Fri Aug 29 04:35:05 2014
######################################################################

TEMPLATE = app
TARGET = exe

QT += core gui widgets

INCLUDEPATH += .

# Input
SOURCES += main.cpp
