######################################################################
# Automatically generated by qmake (3.0) Tue Sep 2 01:14:05 2014
######################################################################

TEMPLATE = app
TARGET = exe

QT += core

INCLUDEPATH += .

# Input
HEADERS += employee.hpp
SOURCES += employee.cpp main.cpp
